services:
  worker:
    build: .
    restart: unless-stopped
    volumes:
      - ~/.cache:/root/.cache
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
